### ISSUE TITLE
local variable 'weighted_missed' referenced before assignment

### ISSUE THREAD

**Issue by mw55309** [dib-lab/sourmash#464] opened 2018-04-23 14:58 UTC
Hi

I'm getting an error after installing sourmash via conda (so we have version 2.0.0a4)

The error is:

```sh
loaded query: mags/bin.1201.fa... (k=31, DNA)
loaded 1 databases.                                                            31.sbt.json
found less than 2.0 kbp in common. => exiting
Traceback (most recent call last):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/2585c44b/bin/sourmash", line 6, in <module>
    sys.exit(sourmash_lib.__main__.main())
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/2585c44b/lib/python3.5/site-packages/sourmash_lib/__main__.py", lin
e 76, in main
    cmd(sys.argv[2:])
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/2585c44b/lib/python3.5/site-packages/sourmash_lib/commands.py", lin
e 977, in gather
    (1 - weighted_missed) * 100)
UnboundLocalError: local variable 'weighted_missed' referenced before assignment
```

If the answer is I need to upgrade sourmash to latest version, my response would be "is the latest / fixed version available as a conda recipe"?

Cheers
Mick

**Comment by ctb** [comment] 2018-04-23 15:41
Fixed in https://github.com/dib-lab/sourmash/pull/463, just yesterday!

@luizirber what's the process for getting it into an updated conda recipe - bump the version number and file something over in bioconda, maybe here? https://github.com/bioconda/bioconda-recipes/tree/master/recipes/sourmash

**Comment by luizirber** [comment] 2018-04-23 16:06
We can bump the build number and SHA hashes, or do a 2.0.0a5. The former is easier, the latter is cleaner =)

**Comment by ctb** [comment] 2018-04-23 16:07
I'll do a 2.0.0a5 when I can.

**Comment by mw55309** [comment] 2018-04-23 16:16
Love you guys.

Just to let you know - I currently have a paper *under review* that relies on conda sourmash working, so no pressure, but basically it's going to kill my career if you don't fix it #sadface 

Cheers
Mick

**Comment by standage** [comment] 2018-04-23 16:50
> so no pressure, but basically it's going to kill my career if you don't fix it

GDD: guilt-driven development. Maybe I should try this some time! :-)

**Comment by mw55309** [comment] 2018-04-24 08:11
Thanks for the rapid work on this.  However, I now get a different error.  I recreated the query sigs from scratch but used the same GenBank database.  Do I need to update that too?

```
loaded query: mags/bin.371.fa... (k=31, DNA)
loaded 1 databases.
Traceback (most recent call last):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/bin/sourmash", line 6, in <module>
    sys.exit(sourmash_lib.__main__.main())
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/__main__.py", line 76, in main
    cmd(sys.argv[2:])
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/commands.py", line 962, in gather
    for result, weighted_missed, new_max_hash, next_query in gather_databases(query, databases, args.threshold_bp, args.ignore_abundance):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/search.py", line 145, in gather_databases
    best_similarity, best_leaf, filename = find_best(databases, query)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/search.py", line 109, in find_best
    for leaf in tree.find(search_fn, query, 0.0):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/sbt.py", line 191, in find
    if search_fn(node_g, *args):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/sbtmh.py", line 191, in search
    matches = sum(1 for value in mins if node.data.get(value))
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/sbtmh.py", line 191, in <genexpr>
    matches = sum(1 for value in mins if node.data.get(value))
AttributeError: 'SourmashSignature' object has no attribute 'get'

```

Commands are of the form:

```
sourmash compute --scaled 1000 -k 31 -o mag.sig mag.fa
sourmash gather -k 31 mag.sig genbank.json -o mag.csv > mag.out
```

**Comment by mw55309** [comment] 2018-04-24 14:08
Just redownloaded the Genbank files linked from the blog, and the error remains, so it's not that

**Comment by mw55309** [comment] 2018-04-24 14:09
There may be a clue when trying sourmash search:

```

Traceback (most recent call last):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/bin/sourmash", line 6, in <module>
    sys.exit(sourmash_lib.__main__.main())
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/__main__.py", line 76, in main
    cmd(sys.argv[2:])
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/commands.py", line 779, in search
    args.best_only)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/search.py", line 47, in search_databases
    for leaf in tree.find(search_fn, query, threshold):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/sbt.py", line 191, in find
    if search_fn(node_g, *args):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/sbtmh.py", line 96, in search_minhashes
    raise Exception('cannot do similarity search on this SBT; need to rebuild.')
Exception: cannot do similarity search on this SBT; need to rebuild.
```

Note **cannot do similarity search on this SBT; need to rebuild.**

**Comment by ctb** [comment] 2018-04-24 14:16
how about these?

https://sourmash.readthedocs.io/en/latest/databases.html

**Comment by ctb** [comment] 2018-04-24 14:29
ok, excellent, thanks for clarification.

One last request - could you try this out in a clean conda install?

**Comment by mw55309** [comment] 2018-04-24 14:32
So this is all carried out within Snakemake with --use-conda and a clean directory, so it recreates the conda env each time.

Though in the yaml I specify 

```
sourmash=2.0.0a5=py35_0
```

Maybe there are particular versions of dependencies I should specify?

**Comment by ctb** [comment] 2018-04-24 14:33
that seems correct to me. I was worried about stale versions of sourmash.

**Comment by luizirber** [comment] 2018-04-24 20:55
I generated new SBTs a while back, but didn't test then thoroughly yet.
If you want to try (I can't really do much before Wed next week...), this is the link:
https://s3-us-west-2.amazonaws.com/sourmash-databases/genbank-d2-k31.tar.gz

(and you can replace 
`genbank` with `refseq`, 
and `k31`
with `k21` and `k51`)

**Comment by ctb** [comment] 2018-04-25 01:32
but I am very curious as to why this is happening. I use the existing gen bank stuff routinely myself and haven’t run into this problem recently. I will see if I can replicate.

**Comment by ctb** [comment] 2018-04-25 15:24
@mw55309 could you drop me the query .sig file that you are using? thx!

**Comment by ctb** [comment] 2018-04-25 15:24
(I do not see the problem with another query)

**Comment by mw55309** [comment] 2018-04-25 20:17
Thanks, I can confirm that the above error remains even with the new genbank db provided by @luizirber 

```
loaded query: mags/bin.674.fa... (k=31, DNA)
loaded 1 databases.
Traceback (most recent call last):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/bin/sourmash", line 6, in <module>
    sys.exit(sourmash_lib.__main__.main())
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/__main__.py",
 line 76, in main
    cmd(sys.argv[2:])
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/commands.py",
 line 962, in gather
    for result, weighted_missed, new_max_hash, next_query in gather_databases(query, databases, args.threshold_bp, args.ignore_abundance):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/search.py", l
ine 145, in gather_databases
    best_similarity, best_leaf, filename = find_best(databases, query)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/search.py", l
ine 109, in find_best
    for leaf in tree.find(search_fn, query, 0.0):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/sbt.py", line
 191, in find
    if search_fn(node_g, *args):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/sbtmh.py", li
ne 191, in search
    matches = sum(1 for value in mins if node.data.get(value))
  File "/exports/cmvm/eddie/eb/groups/watson_grp/MAGpy_test/MAGpy/.snakemake/conda/0fc7c9fa/lib/python3.5/site-packages/sourmash/sbtmh.py", li
ne 191, in <genexpr>
    matches = sum(1 for value in mins if node.data.get(value))
AttributeError: 'SourmashSignature' object has no attribute 'get'
```

Have sent you sigs and fasta

**Comment by ctb** [comment] 2018-04-25 20:45
Hmm, I get:

sourmash gather bin.1013.sig ../genbank/genbank-k31.sbt.json
select query k=31 automatically.
loaded query: mags/bin.1013.fa... (k=31, DNA)
loaded 1 databases.

found less than 4.0 kbp in common. => exiting

found 0 matches total;
the recovered matches hit 0.0% of the query

So it works for me!?!

ok, I'll have to run this all in an isolated cloud environment.
Are there magpy install instructions I should look at?

**Comment by mw55309** [comment] 2018-04-25 20:52
It's running in the MAGpy-3.5 env here: https://github.com/WatsonLab/MAGpy/tree/master/envs

In theory recreating that env should set you up with what I am running

**Comment by ctb** [comment] 2018-04-26 02:34
replicated with a straight conda env!

@luizirber the problem is that `if isinstance(node, SigLeaf):` (sbtmh.py, line 184) is failing because `node` is of type `sourmash.sbtmh.SigLeaf`, not `SigLeaf`. So this is some weird namespace issue with Python. Any ideas?

**Comment by ctb** [comment] 2018-04-26 02:51
ok and when I do

```
import sourmash.sbtmh
print(sourmash.sbtmh.SigLeaf
```

I get
```
<class 'sourmash_lib.sbtmh.SigLeaf'>
```

so clearly our wonky sourmash/sourmash_lib import stuff is causing the problem in python 3.5.5, which is the version I'm running in this conda install. Humm humm.

**Comment by mw55309** [comment] 2018-04-26 09:40
Is there a version of Python where the problem doesn't exist?

**Comment by ctb** [comment] 2018-04-26 11:07
checking python3.6 now; that's what I develop under.  I don't know if it's
a python3.5 vs 3.6 problem, I was just trying to be overly precise :)

but in any case, I think I figured out the problem; it's bioconda-recipe
related, not sourmash related. fixing now.

**Comment by ctb** [comment] 2018-04-26 11:10
Updated the bioconda recipe to reflect `import sourmash` instead of `import sourmash_lib`; see https://github.com/bioconda/bioconda-recipes/pull/8746.

**Comment by ctb** [comment] 2018-04-26 11:11
Briefly, to replicate the bug, all I did was:

```
~/miniconda3/bin/conda create -n magpy2 sourmash=2.0.0a5 python=3.6
source ~/miniconda3/bin/activate magpy2
sourmash gather bin.1013.sig ../genbank/genbank-k31.sbt.json 
```

for me this broke in both python3.5 and python3.6. The clue was that the only place sourmash_lib wass ever referenced was in the bioconda recipe :)

**Comment by mw55309** [comment] 2018-04-26 12:44
Thanks for looking in to this

I note that on bioconda (https://anaconda.org/bioconda/sourmash) version v2.0.0a6 is against Mac, but v2.0.0a5 against Linux.

Was this deliberate?  Or is it still working through the system? cc @bgruening

**Comment by bgruening** [comment] 2018-04-26 12:54
@ctb should be online now. OSX build takes slightly longer then Linux builds. https://anaconda.org/bioconda/sourmash/files

**Comment by ctb** [comment] 2018-04-26 15:12
thank you, and it now all works for me! whew.

**Comment by ctb** [comment] 2018-04-29 12:57
@mw55309 confirmed this was fixed for them as well. Closing!

**Closed by ctb** 2018-04-29 12:57 UTC
