### ISSUE TITLE
"self-recognition" in SBT

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#133] opened 2017-02-17 08:02 UTC
Dear all,

I have two questions about the SBT "behaviour":

1.

I noticed this behaviour and just wanted to confirm: Given a minhash signature of name "foobar" indexed in an SBT. If the same signature is then used as query against the SBT, it will not "find itself", i.e. this will not happen:

```
loaded query: FOOBAR... (k=16, DNA)
for FOOBAR, found: 1.00 FOOBAR
```

Correct? Here's the full "test":

```
$ sourmash sbt_search -k 16 test control.json
# running sourmash subcommand: sbt_search
loaded query: ID1... (k=16, DNA)
1.00 ID1
0.96 ID2
0.96 ID3
0.92 ID4
0.92 ID5
$ sourmash categorize -k 16 test control.json
# running sourmash subcommand: categorize
found 1 files to query
loaded query: ID1... (k=16, DNA)
for ID1, found: 0.96 ID2
```

2. 

When using `sourmash sbt_search` with a given treshold, does the command do an extensive search of the whole SBT (i.e. going through each leaf) or does it stop if some node does not pass the threshold?

As always, many thx for your help.

**Comment by viehwegerlib** [comment] 2017-02-17 11:23
Update:

It seems I was wrong and indeed if a query sequence in present in the SBT as well, it will "self recognize". However, I would expect a similarity of one in this case, but this is not the case, e.g.

```
# running sourmash subcommand: categorize
found 1 files to query
...sig loading 14
loaded query: CY146537... (k=16, DNA)
for CY146537, found: 0.98 CY146537
loaded query: GQ907350... (k=16, DNA)
for GQ907350, found: 0.20 CY184063
loaded query: CY132877... (k=16, DNA)
for CY132877, found: 0.98 CY132877
loaded query: KT449577... (k=16, DNA)
for KT449577, found: 0.94 KT449590
loaded query: CY130356... (k=16, DNA)
for CY130356, found: 0.98 CY079878
loaded query: KU289794... (k=16, DNA)
for KU289794, found: 0.98 KU289794
loaded query: KX013042... (k=16, DNA)
for KX013042, found: 0.80 KX013079
loaded query: CY127783... (k=16, DNA)
for CY127783, found: 0.94 CY127774
loaded query: CY117485... (k=16, DNA)
for CY117485, found: 0.96 CY117485
loaded query: EU500844... (k=16, DNA)
for EU500844, found: 0.94 EU500844
loaded query: KT589224... (k=16, DNA)
for KT589224, found: 0.74 CY088713
loaded query: HM172113... (k=16, DNA)
for HM172113, found: 0.66 EU195408
loaded query: CY127536... (k=16, DNA)
for CY127536, found: 0.98 CY127536
loaded query: CY205219... (k=16, DNA)
for CY205219, found: 0.96 KX013086
loaded query: JN852795... (k=16, DNA)
for JN852795, found: 0.94 JN852803
```

Has this to do with the false positives in a Bloom filter, i.e. some k-mers being falsely accepted by the BF?

**Comment by ctb** [comment] 2017-02-17 14:05
That's strange -- when you search it against itself using 'sourmash search',
what is the similarity?  They should match.

**Comment by viehwegerlib** [comment] 2017-02-17 14:17
Sometimes they match, sometimes not:

```
comparison:

line 1: sourmash sbt_search, first hit
line 2: categorize

FJ986622.search: 0.88 CY158297
for FJ986622, found: 0.88 CY158297

FJ986621.search: 1.00 EU604689
for FJ986621, found: 0.98 GQ484355

FJ986618.search: 0.92 CY099077
for FJ986618, found: 0.92 CY099077

FJ986619.search: 0.90 CY158873
for FJ986619, found: 0.90 CY158873

FJ986620.search: 1.00 EU604689
for FJ986620, found: 0.98 GQ484355
```

**Comment by ctb** [comment] 2017-02-17 14:24
Sorry, can you try `sourmash search` directly? sbt_search goes through
the SBT code; sourmash search just does the straight-up comparison
of the two signature files.  You may have to use '-f' to get it to
compare against itself.

And to be clear, in either case if two signature files are constructed
from the same input sequence, they should have 100% match - so if that's
not happening, it's a bug :).  If they're constructed from different
input sequences that are supposed to be the same, then maybe the sequences
are not actually the same.

I don't immediately understand what the different names are in your output,
BTW.  Which ones are supposed to be identical?

**Comment by viehwegerlib** [comment] 2017-02-17 14:38
The IDs are GenBank IDs.

The sequences from pair 2 and 5 are the same, one problem less. Still, I tried sourmash compare, but same thing:

```
$ sourmash search -k 16 error.json ha.json
# running sourmash subcommand: search
loaded query: FJ986621... (k=16, DNA)
loading db of signatures from 1 files
...sig loading 31,394
loaded 31395 signatures total.
7856 matches; showing 3:
	 EU604689 	 1.000 	 ha.json
	 GQ484355 	 0.980 	 ha.json
	 CY099159 	 0.960 	 ha.json

$ sourmash categorize ha.sbt.json error.json
# running sourmash subcommand: categorize
found 1 files to query
loaded query: FJ986621... (k=16, DNA)
for FJ986621, found: 0.98 GQ484355
```

**Comment by ctb** [comment] 2017-02-17 14:41
that is really Not Good. thanks for reporting!

@brooksph @luizirber can one of you follow up pls? I'm teaching today :)

**Comment by ctb** [comment] 2017-02-18 13:58
Does this match what you see when you run on these sequences?

```
% ls
EU604689.fa     FJ986621.fa
% sourmash compute -k 16 --name-from-first *.fa
# running sourmash subcommand: compute
computing signatures for files: EU604689.fa, FJ986621.fa
Computing signature for ksizes: [16]
Computing only DNA (and not protein) signatures.
Computing a total of 1 signatures.
Computing signature for ksizes: [16]
... reading sequences from EU604689.fa
calculated 1 signatures for 1 sequences in EU604689.fa
... reading sequences from FJ986621.fa
calculated 1 signatures for 1 sequences in FJ986621.fa

% sourmash search *.sig -k 16
# running sourmash subcommand: search
loaded query: EU604689.1 Influenza A virus (... (k=16, DNA)
loading db of signatures from 1 files
loaded 1 signatures total.
1 matches; showing 3:
         FJ986621.1 ...     0.944   FJ986621.fa.sig
```

**Comment by viehwegerlib** [comment] 2017-02-18 22:31
Yes, its the same.

```
$ sourmash compute -k 16 --name-from-first *.fa
# running sourmash subcommand: compute
computing signatures for files: EU604689.fa, FJ986621.fa
Computing signature for ksizes: [16]
Computing only DNA (and not protein) signatures.
Computing a total of 1 signatures.
Computing signature for ksizes: [16]
... reading sequences from EU604689.fa
calculated 1 signatures for 1 sequences in EU604689.fa
... reading sequences from FJ986621.fa
calculated 1 signatures for 1 sequences in FJ986621.fa

$ sourmash search *.sig -k 16
# running sourmash subcommand: search
loaded query: EU604689.1 Influenza A virus (... (k=16, DNA)
loading db of signatures from 1 files
loaded 1 signatures total.
1 matches; showing 3:
	 FJ986621.1 Influenza A virus (A/Ohio/02/2007(H1N1)) segment 4 hemagglutinin (HA) gene, complete cds 	 0.944 	 FJ986621.fa.sig
```

Note some other behaviour I observed: When running `sourmash sbt_search` (default threshold=0.08) I get the same number of hits as with `sourmash search`, and the similarity scores match, but the former duplicates some IDs:

```
sourmash sbt_search   sourmash search
CY180652 0.74         CY180652 0.74
CY185713 0.72         CY185713 0.72
CY005974 0.68         CY005975 0.68
CY005974 0.68         CY005974 0.68
CY014721 0.66         CY014721 0.66
CY014778 0.64         CY014778 0.64
GU186610 0.64         GU186610 0.64
CY180644 0.62         CY180644 0.62
CY185721 0.60         CY178206 0.60
CY179515 0.60         CY178190 0.60
CY179515 0.60         CY179507 0.60
CY179515 0.60         CY179523 0.60
CY179515 0.60         CY179531 0.60
CY179515 0.60         CY179499 0.60
CY179515 0.60         CY178198 0.60
CY179515 0.60         CY178855 0.60
CY179515 0.60         CY179515 0.60
CY179515 0.60         CY185721 0.60
CY178486 0.58         CY178486 0.58
CY005978 0.54         CY014587 0.54
CY005978 0.54         CY005978 0.54
CY014587 0.54         CY185729 0.54
CY177480 0.50         CY177480 0.50
CY021621 0.48         CY021621 0.48
CY005980 0.48         CY005980 0.48
CY178911 0.46         CY178911 0.46
CY005928 0.44         CY185829 0.44
CY005928 0.44         CY005928 0.44
CY139929 0.38         CY185969 0.38
```

**Comment by ctb** [comment] 2017-02-19 15:06
Yes, `sbt_categorize` ignores signature records that are identical (see line `if leaf.data.md5sum() != query.md5sum():` in `sourmash_lib/commands.py`. This seems like good default behavior but we can provide a command-line override if you like? If that is of interest, create a new issue with just a link to this comment ;).

Point 3/weird behavior with `sbt_search` vs `search` looks like a (serious!) bug to me, but looking at the code there is no obvious reason why. Yay bugs! Would you be able to send us the files (maybe attached to this issue? not sure if that works. or dropboxed?) & commands to reproduce it?

thx!

**Comment by viehwegerlib** [comment] 2017-02-19 21:45
Really appreciate your looking into this. Following is the code used to generate my results. I sent the input and intermediate data (including SBT and all) using `wetransfer.com` to titus@idyll.org (you'll get a link with an invitation to the download).

```
# 1. Minhash reference "data", create SBT.

sourmash compute -k 16 -n 50 --singleton data.fa
# running sourmash subcommand: compute
computing signatures for files: data.fa
Computing signature for ksizes: [16]
Computing only DNA (and not protein) signatures.
Computing a total of 1 signatures.
Computing signature for ksizes: [16]
calculated 32172 signatures for 32172 sequences in data.fa

sourmash sbt_index index data.fa.sig
# running sourmash subcommand: sbt_index
loading 1 files into SBT
...sig loading 32,171
loaded 32172 sigs; saving SBT under "index"



# 2. Minhash query. I verified using some Python code that the query is present in the reference data and has exactly the same sequence.

sourmash compute -k 16 -n 50 query.fa
# running sourmash subcommand: compute
computing signatures for files: query.fa
Computing signature for ksizes: [16]
Computing only DNA (and not protein) signatures.
Computing a total of 1 signatures.
Computing signature for ksizes: [16]
... reading sequences from query.fa
calculated 1 signatures for 1 sequences in query.fa



# 3. sourmash categorize, sbt_search, search

sourmash categorize index query.fa.sig
# running sourmash subcommand: categorize
found 1 files to query
loaded query: query.fa... (k=16, DNA)
for query.fa, found: 0.94 EU982316

sourmash sbt_search -k 16 index.sbt.json query.fa.sig > result.sbt_search
# running sourmash subcommand: sbt_search
loaded query: query.fa... (k=16, DNA)

# There are duplicates.
wc -l result.sbt_search
489 result.sbt_search
cut -f2 -d' ' result.sbt_search | sort | uniq | wc -l
442

sourmash search \
-k 16 --save-matches result.search.sig -n 489 \
query.fa.sig data.fa.sig > result.search
# running sourmash subcommand: search
loaded query: query.fa... (k=16, DNA)
loading db of signatures from 1 files
...sig loading 32,171
loaded 32172 signatures total.
489 matches; showing 3:
     CY006042    1.000   data.fa.sig
     EU982316    0.940   data.fa.sig
     CY180708    0.840   data.fa.sig
saving all matches to "result.search"

# bit of manual manipulation of result.search because format weird (irregular delimiters), then
cut -f1 result.search | sort | uniq | wc -l
489
# i.e. no duplicates
```

**Comment by ctb** [comment] 2017-02-19 21:58
got the file, thanks!

**Comment by viehwegerlib** [comment] 2017-02-24 09:38
Is the behaviour reproducible from the data I sent?

**Comment by ctb** [comment] 2017-02-28 05:44
Yes, I think so! (Sorry to take so long - didn't realize it had been well over a week!)

```
% ../sourmash sbt_search ./index query.fa.sig --dna -k 16 > sbt_search_foo
%  cut -d\  -f2 sbt_search_foo | sort |uniq -d
AB753217
CY031283
CY038458
CY041274
CY043912
CY101390
CY116614
CY144373
DQ064364
DQ465400
EF492234
EU516312
FJ534538
GQ120549
KF142481
KF259139
KF259141
KF259144
KF881386
KF971949
KF971957
KF971981
KF972021
KF972037
KF972101
KF972109
KP414541
KP414718
KP415559
KP865949
KU311592
KX377330
KX859398
KX859405
KX859406
KX867825
```

I have also verified that `KF972037` does not appear in multiple locations in the SBT, so it's not case where that signature, at least, has been added in two separate files.

Just to confirm, @viehwegerlib, this looks like a bug in `sbt_search` specifically, right?

**Comment by ctb** [comment] 2017-02-28 05:53
@luizirber this appears to be caused by a problem in the SBT code where there are multiple `node_p` for the same leaf node. Hence the `visited` set in `SBT::find(...)` does not accurately block it from being visited more than once. Any thoughts?

happy to pass the data over to you.

**Comment by viehwegerlib** [comment] 2017-02-28 08:43
> Just to confirm, @viehwegerlib, this looks like a bug in sbt_search specifically, right?

Yes, I think so. `sourmash search` works as expected.

**Comment by luizirber** [comment] 2017-02-28 18:33
I will take a look

**Comment by ctb** [comment] 2020-04-08 13:10
hi @phiweger I managed to lose track of this, sorry. Do you still have these files around? I'd like to take a look at it again if possible.

**Comment by ctb** [comment] 2020-05-03 13:47
Closing for now.

**Closed by ctb** 2020-05-03 13:47 UTC
Labels: sbt
