### ISSUE TITLE
Issue with LCA taxonomy tutorial and query size

### ISSUE THREAD

**Issue by RemiMaglione** [dib-lab/sourmash#1106] opened 2020-07-16 20:07 UTC
Hello, 
I'm trying to use sourmash (for taxonomic annotation) and didn't succeed with my own data so far. 
However, I gave a try to the "LCA to do taxonomic" tutorial. It worked well and I decided to try with another test genome (an E.coli found by blasting a random sequence of my actual datasets: https://www.ncbi.nlm.nih.gov/nuccore/CP053602.1?report=fasta). 
`sourmash compute -k 31 --scaled=1000 --name-from-first ecoli.fa`
`sourmash lca classify --db /db/genbank-k31.lca.json --query ecoli.fa.sig`
it woked too

But, most of my sequence/genome are smaller than those genomes, so i decided to shop their sequence:
- My random E.Coli at 1000 nucleotides:
```
head -16 ecoli.fa > ecoli_1k.fa
sourmash compute -k 31 --scaled=1000 --name-from-first ecoli_1k.fa
sourmash lca classify --db /db/genbank-k31.lca.json --query ecoli_1k.fa.sig
```

- The tutorial genome at 1kb
```
gunzip -c some-genome.fa.gz | head -14 > test_1k.fa
sourmash compute -k 31 --scaled=1000 --name-from-first test_1k.fa
sourmash lca classify --db /db/genbank-k31.lca.json --query test_1k.fa.sig
```

- and the tutorial genome at 10kb:
```
gunzip -c some-genome.fa.gz | head -126 > test_10k.fa
sourmash compute -k 31 --scaled=1000 --name-from-first test_10k.fa
sourmash lca classify --db /db/genbank-k31.lca.json --query test_10k.fa.sig
```

All failed to be annotated: only '**nomatch**'. 

So long story, short question: **Why ? Does it mean that I cannot use sourmash for taxonomic annotation if the query sequence is "too short" ?** (it doesn't make sens to me, even 1kb should be sufficient to have, at least, a hit at a lower taxonomic level). Or did I do something wrong ? 

Any help will be appreciated,
Best, 
Rémi

**Comment by ctb** [comment] 2020-07-16 20:14
hi Rémi, the problem is that the LCA databases are built at scaled=10k, I bet! And even if there is one or two matching k-mers, the default threshold for `lca classify` is something like 5 - you can try using `--threshold=0` to see what happens with your longer sequence.

I hope that helps - I'll take a look at how to improve the docs!

**Comment by RemiMaglione** [comment] 2020-07-16 20:55
Hi ctb, 
thanks for your input. I didn't worked, but I came back with another question: 
does it mean that I should scaled the LCA database below (or equal) to my query sequence length ?

**Comment by ctb** [comment] 2020-07-17 14:49
hi @RemiMaglione --

The safest is to set scaled to be ~1/5th your minimum query sequence length. However, this can make databases very large; all of our pre-computed databases are either scaled=1000 (for the SBTs) or scaled=10000 (for LCAs).

You can read a bit more [here](https://sourmash.readthedocs.io/en/latest/using-sourmash-a-guide.html#what-resolution-should-my-signatures-be-how-should-i-compute-them).

Let me know as you have questions!

**Comment by ctb** [comment] 2020-07-18 14:08
also see discussion/response in https://github.com/dib-lab/sourmash/issues/923

**Comment by RemiMaglione** [comment] 2020-07-20 21:50
Hi @ctb , 
thanks for that input too. I'm now wondering if you could gave me a link of the non-computed database so I can do comparison between different scaling ? Also, does a lower scaling will exponentially or linearly increase the RAM memory needed ?

**Comment by ctb** [comment] 2020-07-22 14:33
hi @RemiMaglione I don't have the raw sequences handy - but I realized you don't really need them, I think :). if you do `sourmash compute` on your query sequences to build signatures with various scaled parameters, and then run `sourmash sig describe` on those signatures, you can see exactly how many hashes are chosen for your input sequence(s) and that should tell you how parameters work.

This rests on the following detail: if a hash is chosen for a sequence, that sequence is detectable; if multiple hashes are chosen, that sequence is robustly detectable. There's no higher order logic, really; it's all about number of hashes... 

lower scaling should linearly or sublinearly increase RAM in LCA databases; 'sublinearly' because if there are shared hashes between sequences in the database, memory requirements should drop.

**Comment by ctb** [comment] 2021-01-10 15:05
closing for now. ask questions as you have them!

**Closed by ctb** 2021-01-10 15:05 UTC
